version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: menugourmet-app
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: menugourmet-db
    restart: always
    tty: true
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  pgadmin:
    image: dpage/pgadmin4
    container_name: menugourmet-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    depends_on:
      - db